### ISSUE TITLE
Game crashed when I tried to clear item filter list

### ISSUE THREAD

**Issue by foodtooth** [North-West-Wind/forge-autofish#6]
**Describe the bug**
I found that Rotten flesh has been filtered by default so I clicked it to reenable, but crashed

**To Reproduce**
Click config and search rotten and click to remove it

**Expected behavior**
game not crash and filter list saved :P

**Screenshots**
Sorry I don't. but I do have some crash log here

> [01:04:15] [Server thread/INFO] [minecraft/MinecraftServer]: foodtooth has made the advancement [Fishy Business]
> [01:04:15] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] foodtooth has made the advancement [Fishy Business]
> [01:04:15] [Render thread/INFO] [minecraft/AdvancementList]: Loaded 151 advancements
> [01:04:27] [Render thread/INFO] [minecraft/AdvancementList]: Loaded 154 advancements
> [01:04:43] [Thread-0/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file D:\micha\bin\MultiMC\instances\1.16.5\.minecraft\config\forgeautofish-client.toml is not correct. Correcting
> [01:04:59] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 4ac9c5d6-52fc-4384-be9f-627d14822237
> [01:05:00] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
> [01:05:00] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
> [01:05:00] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: foodtooth lost connection: Disconnected
> [01:05:00] [Server thread/INFO] [minecraft/MinecraftServer]: foodtooth left the game
> [01:05:00] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: Stopping singleplayer server as player logged out
> [01:05:00] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
> [01:05:00] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[Fate]'/minecraft:overworld
> [01:05:01] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (Fate): All chunks are saved
> [01:05:01] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[Fate]'/minecraft:the_nether
> [01:05:01] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
> [01:05:01] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[Fate]'/minecraft:the_end
> [01:05:01] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
> [01:05:01] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (Fate): All chunks are saved
> [01:05:01] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
> [01:05:01] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
> [01:05:02] [Render thread/INFO] [STDOUT/]: [xaero.map.WorldMapSession:cleanup:44]: World map session finalized.
> [01:05:02] [Render thread/INFO] [STDOUT/]: [xaero.common.XaeroMinimapSession:cleanup:67]: Minimap session finalized.
> [01:05:02] [Render thread/FATAL] [minecraft/Minecraft]: Reported exception thrown!
> net.minecraft.crash.ReportedException: Rendering screen
> 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:505) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.0.42-launcher.jar:36.0] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
> 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
> Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -30 out of bounds for length 0
> 	at ml.northwestwind.forgeautofish.config.gui.SuperFilterScreen.func_230430_a_(SuperFilterScreen.java:107) ~[forgeautofish:2.0.3-1.16.x] {re:classloading}
> 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:290) ~[forge:?] {re:classloading}
> 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:runtimedistcleaner:A}
> 	... 22 more
> [01:05:02] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: ---- Minecraft Crash Report ----
> // I let you down. Sorry :(
> 
> Time: 2/20/21, 1:05 AM
> Description: Rendering screen
> 
> java.lang.ArrayIndexOutOfBoundsException: Index -30 out of bounds for length 0
> 	at ml.northwestwind.forgeautofish.config.gui.SuperFilterScreen.func_230430_a_(SuperFilterScreen.java:107) ~[forgeautofish:2.0.3-1.16.x] {re:classloading}
> 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:290) ~[forge:?] {re:classloading}
> 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.0.42-launcher.jar:36.0] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
> 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at ml.northwestwind.forgeautofish.config.gui.SuperFilterScreen.func_230430_a_(SuperFilterScreen.java:107) ~[forgeautofish:2.0.3-1.16.x] {re:classloading}
> 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:290) ~[forge:?] {re:classloading}
> -- Screen render details --
> Details:
> 	Screen name: ml.northwestwind.forgeautofish.config.gui.SuperFilterScreen
> 	Mouse location: Scaled: (247, 51). Absolute: (991.000000, 207.000000)
> 	Screen size: Scaled: (480, 251). Absolute: (1920, 1001). Scale factor of 4.000000
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [ClientPlayerEntity['foodtooth'/34, l='ClientLevel', x=-205.91, y=63.00, z=-654.16]]
> 	Chunk stats: Client Chunk Cache: 841, 575
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (217,63,-137), Chunk: (at 9,3,7 in 13,-9; contains blocks 208,0,-144 to 223,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
> 	Level time: 48375 game time, 82425 day time
> 	Server brand: forge
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.0.42-launcher.jar:36.0] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
> 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
> 
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.16.5
> 	Minecraft Version ID: 1.16.5
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 15.0.2, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
> 	Memory: 143270368 bytes (136 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
> 	CPUs: 4
> 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
> 	ModLauncher: 8.0.9+86+master.3cf110c
> 	ModLauncher launch target: fmlclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		/mixin-0.8.2.jar mixin PLUGINSERVICE 
> 		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
> 		/forge-1.16.5-36.0.42-launcher.jar object_holder_definalize PLUGINSERVICE 
> 		/forge-1.16.5-36.0.42-launcher.jar runtime_enum_extender PLUGINSERVICE 
> 		/forge-1.16.5-36.0.42-launcher.jar capability_inject_definalize PLUGINSERVICE 
> 		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
> 		/forge-1.16.5-36.0.42-launcher.jar runtimedistcleaner PLUGINSERVICE 
> 		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
> 		/forge-1.16.5-36.0.42-launcher.jar fml TRANSFORMATIONSERVICE 
> 	FML: 36.0
> 	Forge: net.minecraftforge:36.0.42
> 	FML Language Providers: 
> 		javafml@36.0
> 		minecraft@1
> 	Mod List: 
> 		forge-1.16.5-36.0.42-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
> 		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |DONE      |NOSIGNATURE
> 		Bookshelf-1.16.5-10.0.1.jar                       |Bookshelf                     |bookshelf                     |10.0.1              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
> 		EnchantmentDescriptions-1.16.5-7.0.3.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.3               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
> 		forge-1.16.5-36.0.42-universal.jar                |Forge                         |forge                         |36.0.42             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
> 		forgeautofish-2.0.3-1.16.x.jar                    |AutoFish for Forge            |forgeautofish                 |2.0.3               |DONE      |NOSIGNATURE
> 		Xaeros_Minimap_21.3.0.2_Forge_1.16.5.jar          |Xaero's Minimap               |xaerominimap                  |21.3.0              |DONE      |NOSIGNATURE
> 		XaerosWorldMap_1.12.0.2_Forge_1.16.5.jar          |Xaero's World Map             |xaeroworldmap                 |1.12.0              |DONE      |NOSIGNATURE
> 		NaturesCompass-1.16.5-1.8.6.jar                   |Nature's Compass              |naturescompass                |1.16.5-1.8.6        |DONE      |NOSIGNATURE
> 		jei-1.16.4-7.6.1.71.jar                           |Just Enough Items             |jei                           |7.6.1.71            |DONE      |NOSIGNATURE
> 	Crash Report UUID: 4ac9c5d6-52fc-4384-be9f-627d14822237
> 	Launched Version: MultiMC5
> 	Backend library: LWJGL version 3.2.2 build 10
> 	Backend API: Intel(R) HD Graphics 530 GL version 4.6.0 - Build 27.20.100.8681, Intel
> 	GL Caps: Using framebuffer using OpenGL 3.0
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'forge'
> 	Type: Client (map_client.txt)
> 	Graphics mode: fancy
> 	Resource Packs: vanilla
> 	Current Language: English (US)
> 	CPU: 4x Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
> [01:05:02] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: #@!@# Game crashed! Crash report saved to: #@!@# D:\micha\bin\MultiMC\instances\1.16.5\.minecraft\crash-reports\crash-2021-02-20_01.05.02-client.txt

**Comment by North-West-Wind** [comment]
Which version are you running on? (and which Minecraft version)
Cannot reproduce in 1.16

**Comment by BlackwingHawkeye** [comment]
Same here but different screen class. probably a different version.[crash-2021-09-16_14.06.19-client.txt](https://github.com/North-West-Wind/forge-autofish/files/7177522/crash-2021-09-16_14.06.19-client.txt)Mod version: forgeautofish-2.1.2-1.16.x.jar from CurseForge
Game version: 1.16.5
Forge Version: 36.2.4

crash files:
[crash-2021-09-16_08.44.38-client.txt](https://github.com/North-West-Wind/forge-autofish/files/7177462/crash-2021-09-16_08.44.38-client.txt)
[crash-2021-09-16_13.45.16-client.txt](https://github.com/North-West-Wind/forge-autofish/files/7177463/crash-2021-09-16_13.45.16-client.txt)
[crash-2021-09-16_14.06.19-client.txt](https://github.com/North-West-Wind/forge-autofish/files/7177522/crash-2021-09-16_14.06.19-client.txt)

Reproduction steps:
a) open the mod menu sceen by pressing "k" ingame
b) click on "Item Filter"
c) enter anything in the Super Item Filter search field
![2021-09-16_14 05 43](https://user-images.githubusercontent.com/43969903/133609386-3e4675ce-6f2f-4ef1-9418-fd0db6fc359f.png)
d) click on "config"
e) enter something in the search field
![2021-09-16_14 12 56](https://user-images.githubusercontent.com/43969903/133610491-b3fc2042-8453-4b34-8f95-34533ad5d993.png)

First two times it crashed when deleting the last letter. Last time it crashed while I was entering something in the second search field.

Are those two fields somehow accidently interconnected? I think it only crashes when you used both search fields

**Comment by BlackwingHawkeye** [comment]
I don't know how the class TranslatableComponent works but I think it might use the same searchbox instance when initiated with the same values as you do in SuperFilterScreen.java line 52 and FilterSelectionScreen.java line 47. 
Try having a separate TranslatableComponent for the FilterSelectionScreen. Maybe that helps. :)
